sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - docker -v
  - docker-compose -v

script:
  - docker-compose -f docker-compose.yaml config > docker-stack.yaml
  - docker-compose -f docker-stack.yaml build
  - docker-compose -f docker-stack.yaml up -d
  - docker-compose -f docker-stack.yaml ps
  - docker-compose exec -u www-data app composer --version
  - docker-compose -f docker-stack.yaml stop
